import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Title from "./components/title/title";
import Cart from "./cart/cart";
import CartProvider from "./providers/CartProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="lemonade" lang="en">
      <CartProvider>
      <body className={`${inter.className}`}>
        <Title></Title>
        <div  className="px-4">
           {children}
        </div>


       
      </body>
      
      </CartProvider>
    
    </html>
  );
}
